### ISSUE TITLE
which Optix version are you using?

### ISSUE THREAD

**Issue by brabbitdousha** [lcp29/trimesh-ray-optix#1]
Thanks for your work!
When I am trying to use this project, I got a lot of optix errors such as ‘OptixModuleCompileOptions’ {aka ‘struct OptixModuleCompileOptions’} has no member named ‘numPayloadTypes’, I wonder which Optix version are you using? I tried with optix 7.3, and it doesn't work.
besides, you forgot to upload "triro/backend/embedded/shaders_embedded.h", since it's needed

**Comment by brabbitdousha** [comment]
I changed optix version to 7.7, and find triro/backend/embedded/shaders_embedded.h in your commit history, it finally works now

**Comment by lcp29** [comment]
Thank you so much for reporting issues!

I'm currently using OptiX 8.0.0 and after trying different minor versions, I found that the code works since exactly OptiX 7.7.
As for the shader header file, it should have been generated by setup.py at installation. It's not uploaded because I'm not quite sure whether the OptiX binary code would fit all the drivers and environments.

Thank you again for opening this issue. Would you mind opening a pull request for the wrong document?

**Comment by brabbitdousha** [comment]
> Thank you so much for reporting issues!
> 
> I'm currently using OptiX 8.0.0 and after trying different minor versions, I found that the code works since exactly OptiX 7.7. As for the shader header file, it should have been generated by setup.py at installation. It's not uploaded because I'm not quite sure whether the OptiX binary code would fit all the drivers and environments.
> 
> Thank you again for opening this issue. Would you mind opening a pull request for the wrong document?

ok, I've submitted the PR
